import { defineCommand } from '@bunli/core';

const HELP_TEXT = [
  'WhiteBIT CLI',
  '',
  'Usage',
  '  whitebit <group|command> [options]',
  '',
  'Top-level commands',
  '  help                       Show this command help',
  '  completion                 Generate shell completion script',
  '  login                      Interactive login (OpenTUI) and credential save',
  '  ws-token                   Get WebSocket authentication token',
  '  credit-lines               View credit lines',
  '',
  'Root groups',
  '  market                     Market data and platform status',
  '  balance                    Account balance queries',
  '  deposit                    Deposit addresses and refunds',
  '  withdraw                   Crypto and fiat withdrawals',
  '  transfer                   Internal account transfers',
  '  codes                      Redemption codes',
  '  earn                       Staking and yield (fixed, flex, interest)',
  '  trade                      Spot, collateral, and convert trading',
  '  sub-account                Sub-account management',
  '  config                     CLI configuration',
  '',
  'Global options',
  '  --json                     Force JSON output',
  '  --format table|json        Set output format',
  '  --profile <name>           Select profile',
  '  --api-key <key>            Override API key',
  '  --api-secret <secret>      Override API secret',
  '  --api-url <url>            Override API URL',
  '  --verbose, -V              Print request/response diagnostics',
  '  --dry-run                  Print request without sending it',
  '',
  'Examples',
  '  whitebit help',
  '  whitebit completion --shell zsh',
  '  whitebit login',
  '  whitebit market list',
  '  whitebit balance main',
  '  whitebit deposit address BTC BTC',
  '  whitebit earn flex plans',
  '  whitebit earn fixed invest 123 100',
  '  whitebit codes list',
  '  whitebit trade spot limit-order BTC_USDT buy 0.001 50000',
].join('\n');

export const helpCommand = defineCommand({
  name: 'help',
  description: 'Display CLI help text and usage examples',
  handler: async () => {
    process.stdout.write(`${HELP_TEXT}\n`);
  },
});
